[tool.poetry]
name = "your-package-name"
version = "0.1.0"
description = "A brief description of your package"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
