[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "your-package-name"
version = "0.1.0"
description = "A short description of your project"
authors = [
    { name = "Your Name", email = "your_email@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
homepage = "https://github.com/yourusername/yourrepository"
repository = "https://github.com/yourusername/yourrepository"

dependencies = [
    "requests",  # Example dependencies
]

[tool.setuptools.packages.find]
where = ["src"]
