name: Build and Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build twine  # Ensure build and twine are installed

      - name: Build package
        run: |
          python -m build

      - name: Publish to GitHub Packages
        run: |
          pip install twine
          twine upload --repository-url https://upload.github.com/Jomon-Dogu/crypto_trader/packages dist/* --verbose
        env:
          TWINE_USERNAME: ${{ github.actor }}  # GitHub username
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}  # GitHub token from the secrets
