name: Package Python Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # You can adjust the version if needed

      # Step 3: Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build  # Install setuptools, wheel, and build

      # Step 4: Build package using pyproject.toml
      - name: Build package with pyproject.toml
        run: |
          python -m build  # Build the package using pyproject.toml

      # Step 5: Install Twine for publishing
      - name: Install Twine
        run: |
          pip install twine  # Install Twine to upload the package

      # Step 6: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing to GitHub Packages"
          twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
